---

threescale_packagemanifest: 3scale-operator

threescale_subscription_name: 3scale-operator

threescale_automatic_installplan_approval: false
threescale_subscription_starting_csv: ""
threescale_csv_prefix: 3scale-operator

threescale_operator_deployment: 3scale-operator

rolebinding_tekton_sa_edit: tekton-op-sa-edit

tekton_task_threescale_configure_api: threescale-configure-api
tekton_pipeline_threescale_configure_api: threescale-configure-api
pvc_tekton_pipeline_workspace: workspace-pvc
tekton_eventlistener_configure_api: threescale-configure-api
tekton_triggertemplate_configure_api: threescale-configure-api
tekton_triggerbinding_configure_api: threescale-configure-api

tekton_eventlistener_configure_api_service: "el-{{ tekton_eventlistener_configure_api }}"
tekton_eventlistener_configure_api_route: "el-{{ tekton_eventlistener_configure_api }}"
