# vim: set ft=ansible
---

- name: set the username as a fact for easy reuse
  set_fact:
    f_gitea_username: "{{ gitea_generate_user_format | format(item) }}"

- name: check if user exists
  uri:
    url: "https://{{ r_gitea_route.resources[0].spec.host }}/api/v1/users/{{ f_gitea_username }}"
    method: GET
    validate_certs: false
    user: "{{ gitea_admin_user }}"
    password: "{{ gitea_admin_password }}"
    force_basic_auth: true
    status_code: [ 200, 404 ]
  register: r_gitea_insystem_user

- name: create the user
  uri:
    url: "https://{{ r_gitea_route.resources[0].spec.host }}/api/v1/admin/users"
    method: POST
    body: "{{ body }}"
    status_code: 201
    body_format: json
    validate_certs: false
    user: "{{ gitea_admin_user }}"
    password: "{{ gitea_admin_password }}"
    force_basic_auth: true
  vars:
    body: >-
      {
        "email": "{{ f_gitea_username }}@example.com",
        "login_name": "{{ f_gitea_username }}",
        "must_change_password": false,
        "password": "{{ gitea_user_password }}",
        "send_notify": false,
        "username": "{{ f_gitea_username }}"
      }  
  when: r_gitea_insystem_user.status == 404
